services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    # TODO CHANGE API INSECURE
    command: 
      - "--api=true"
      - "--providers.docker"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=sophisticatedmemento@proton.me"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--log.filePath=/traefik/logs/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/traefik/logs/access.log"
      - "--metrics.otlp=true"
      - "--metrics.otlp.http=true"
      - "--metrics.otlp.http.endpoint=http://localhost:4318/v1/metrics"
      - "--tracing=true"
      - "--tracing.otlp=true"
      - "--log.level=DEBUG"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/acme.json:/acme.json
      - /var/log/traefik/traefik.log:/traefik/logs/traefik.log
      - /var/log/traefik/access.log:/traefik/logs/access.log
    restart: unless-stopped
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.svthalexweiler.de`)"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.api.rule=Host(`traefik.svthalexweiler.de`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=kira:$$apr1$$jJPD/8dV$$qT02fiH3.pfzgEasFVIy3."
  clubsoft:
    # ...
    build: .
    labels:
      - traefik.http.routers.clubsoft.rule=Host(`svthalexweiler.de`) || Host(`www.svthalexweiler.de`)
      - traefik.http.routers.clubsoft.tls=true
      - traefik.http.routers.clubsoft.tls.certresolver=myresolver
      - traefik.http.middlewares.httpsredirect.redirectscheme.scheme=https
      - traefik.http.middlewares.httpsredirect.redirectscheme.permanent=true
      - traefik.http.routers.clubsoft.middlewares=httpsredirect
      - traefik.enable=true
    ports:
      - "4321:4321"
